#
# Power save related files
#
obj-y := pm.o runtime.o no_suspend.o

obj-$(CONFIG_DBX500_PRCMU_QOS_POWER) += prcmu-qos-power.o
obj-$(CONFIG_UX500_CONTEXT) 		+= context.o context_arm.o context-db8500.o context-db5500.o
