#
# Power save related files
#
obj-y := pm.o runtime.o

obj-$(CONFIG_U8500_CPUIDLE) 		+= cpuidle.o
obj-$(CONFIG_U8500_CPUIDLE_DEBUG) 	+= cpuidle_dbg.o
obj-$(CONFIG_UX500_CONTEXT) 		+= context.o context_arm.o context-db8500.o context-db5500.o
obj-$(CONFIG_U8500_CPUFREQ) 		+= cpufreq.o
obj-$(CONFIG_UX500_SUSPEND)		+= suspend.o
obj-$(CONFIG_UX500_SUSPEND_DBG)		+= suspend_dbg.o
